### PR TITLE
Bl 931 ux build coder heroes UI kit

### PR DESCRIPTION
**Pull request by savmaxwell93**
## Description

Built a UI Kit so that any future high-fidelity designs will have a solid base to build from.

### Assignees
Savannah Maxwell & Caitlin Talbert

#### Video Link

[Loom Video](https://www.loom.com/share/78f58495693b4bfcb9b0481bf83e5b6b)

#### Jira Link

<blockquote class="jira-card"><a href="https://bloomtechlabs.atlassian.net/browse/BL-931?atlOrigin=eyJpIjoiYTY1MTM1ZGJkMjYyNDQzNDhiNTdjZjAyZGZkMDZmOWYiLCJwIjoiaiJ9">UX: Build CoderHeroes UI Kit</a></blockquote>

## Checklist:

- [x] My design/diagram follows the style guidelines of this project
- [x] My docs are organized within an appropriate folder structure in our repo
- [x] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by JackNunnink — APPROVED** [review]
Great organization

**Review by dpearson00 — APPROVED** [review]
Looks good. Great job.

**Review by Jwatk13 — COMMENTED** [review]
Nice job, clear and organized. Great work!

**Review by AlexiusThomas — APPROVED** [review]
Great job overall, love the clear and concise commit messages and notes.

**Pull request merged**
