### PR TITLE
BL-513-ux-iterate-design-artifacts-to-include-about-and-services-pages

### PR DESCRIPTION
**Pull request by kevkenshi-max**
## Description

___Add your PR description here, deleting this example___

#### Video Link

[Loom Video](Add your loom video link here)

#### Trello Link

___Paste your trello card link here, deleting this example___

(Example below):

<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JfipwNkb&#x2F;265-fix-refactor-sidebar-to-have-icons-representing-each-element-in-the-sidebar">Fix: Refactor sidebar to have icons representing each element in the sidebar</a></blockquote>

## Checklist:

- [ ] My design/diagram follows the style guidelines of this project
- [ ] My docs are organized within an appropriate folder structure in our repo
- [ ] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Comment by kevkenshi-max** [comment]
https://www.loom.com/share/6738928be3c2467288a5bbc39c335ba0

**Comment by savmaxwell93** [comment]
Danny Chui https://github.com/wreck888 is also an assignee on this ticket

**Review by theecolya — APPROVED** [review]
This is cute!!! These pages all look very nice and complimentary.

**Review by lailaarkadan — APPROVED** [review]
The pages that you implemented look clean and easy to read. It also goes with the rest of the website. Good job!

**Review by Epeng1994 — APPROVED** [review]
Design is simple and intuitive for future users!

**Review by jzkime — COMMENTED** [review]
I really like the photos provided! The colors and placement of the components are really pleasing and fun to look at, I'm sure users would appreciate the design decisions. 

A few questions:
Are the photos in the images folder the final design chosen? I saw in the loom video there were different color schemes and was wondering where it tied in. 

Finally, the 'About CoderHeroes' link at the bottom is highlighted blue in all the photos, is that the stylistic choice or is it highlighted as if being hovered over? 

Great work! Very nicely done.

**Comment by savmaxwell93** [comment]
> 
> A few questions: Are the photos in the images folder the final design chosen? I saw in the loom video there were different color schemes and was wondering where it tied in.
> 

I changed the color scheme due to those colors failing an accessibility contrast checker, the ones in the images folder are the final designs chosen pending changes from BL-931

**Pull request merged**
