### PR TITLE
overhaul of the figma design system - co-owner Spencer Longhurst

### PR DESCRIPTION
**Pull request by savmaxwell93**
## Description

Overhauled the figma design system along with Spencer to be one file with two organized pages and layers that can be collapsed with meaningful titles

#### Video Link

https://www.loom.com/share/30bf96351dec41f2884e391f89a29553

#### Jira Link

https://bloomtechlabs.atlassian.net/browse/BL-356?atlOrigin=eyJpIjoiM2I1OTk2YTlmYzkzNDQwY2I5NjUzNGRjODNhOTlkZTEiLCJwIjoiaiJ9

## Checklist:

- [x] My design/diagram follows the style guidelines of this project
- [x] My docs are organized within an appropriate folder structure in our repo
- [x] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by ShahWahidy — APPROVED** [review]
Great work on organizing everything inside a single file. I think it's a great way to look up information and speed up the process. the design as usual is clean and looks great.

**Review by jose-mercado — APPROVED** [review]
When I first got added into CoderHeros, the figma board was all over the place and unorganized, it definitely needed some work. Thanks to you two, the board looks amazing! everything is so neat and organized, MUCH easier to work with.

**Review by leewp8 — APPROVED** [review]
I know how much work you two did on revamping the Figma and it greatly appreciated. Looks so much better and a lot easier to use/flows better.

**Review by kylerostler — APPROVED** [review]
Love the changes, this is a huge improvement as far as organization goes. Great loom video concisely explaining the changes made. Love that everything is in one place now great work on this.

**Review by dirkknibbe — APPROVED** [review]
Perfection! This is super easy to understand and navigate, excellent work.

**Pull request merged**
