### PR TITLE
BL-515 UX: Iterate design artifacts to include class participation

### PR DESCRIPTION
**Pull request by tkordysh**
## Description

Created a reduced scope mockup of the parent dashboard where there is a single table with all registered courses for their account, with each row having a button to join. Also, provided a link to join an active class for children on their mission control page.

#### Video Link

https://www.loom.com/share/a90773554ab4440ca8e5dd1aeb41e040

#### Trello Link

https://bloomtechlabs.atlassian.net/jira/software/c/projects/BL/boards/9?modal=detail&selectedIssue=BL-515&quickFilter=28

## Checklist:

- [X] My design/diagram follows the style guidelines of this project
- [X] My docs are organized within an appropriate folder structure in our repo
- [X] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by Rlauckern — APPROVED** [review]
Nicely done. I like the "join live" option in the student's registered section setup! It's a simple and easy flow to follow.

**Comment by techlando** [comment]
Great job developing UX design and updating Coder-Heroes Docs. Love the JOIN LIVE button, as I want to join now!

**Review by techlando — APPROVED** [review]

**Review by laurensruiz — APPROVED** [review]
I really like the designs. It's eye catching and easy to follow especially for a parent who might be possible seeing this.

**Review by AnthonyLayne — APPROVED** [review]
This is very nice, the table is looks easy to understand, use and is designed well. Great Job!

**Pull request merged**
