### PR TITLE
Bl 473 design for booking and payment flow

### PR DESCRIPTION
**Pull request by AnthonyLayne**
## Description

Designed a booking and payment flow under the assumption of only being able to book one course at a time. These are preliminary designs, it might be updated in the future depending on how the data will look  for each course model.

#### Video Link

(https://www.loom.com/share/2f60b02b95ad41698e165afd6c4bed15)

## Checklist:

- [x] My design/diagram follows the style guidelines of this project
- [x] My docs are organized within an appropriate folder structure in our repo
- [x] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by Rebecca-Stone — APPROVED** [review]
Great job adding the photos and I really liked your loom, it was easy to follow. The only changes I could think of are to add a markdown file with your loom, but I'm not sure if it is required. Again, you guys did great!

**Review by MaxT6 — APPROVED** [review]
Clean designs with easy to understand flow!

**Review by Irving-Delgad0 — APPROVED** [review]
Design looks really clean and easy to follow, awesome job!

**Comment by dshipuk** [comment]
Flow looks great! the filter option looks simple to use. All in all looking good great job!

**Review by dshipuk — APPROVED** [review]
Flow looks great! the filter option looks simple to use. All in all looking good great job!

**Review by Irving-Delgad0 — APPROVED** [review]
Design looks really clean and easy to follow, awesome job!

**Pull request merged**
