### PR TITLE
BL-480 update product doc repository to include updated registration details

### PR DESCRIPTION
**Pull request by tkordysh**
## Description

Adding documentation for updated registration details 

#### Video Link

https://www.loom.com/share/f5873ae705eb4133bbccfdcf015874c0

#### Trello Link

https://bloomtechlabs.atlassian.net/jira/software/c/projects/BL/boards/9?modal=detail&selectedIssue=BL-480&quickFilter=28

## Checklist:

- [X] My design/diagram follows the style guidelines of this project
- [X] My docs are organized within an appropriate folder structure in our repo
- [X] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by leewp8 — APPROVED** [review]
Nice work guys. These types of updates to our docs make it so much easier to get coding work done. So thank you

**Review by Rlauckern — APPROVED** [review]
Good job with organization. It's nice that you can click on each one to go to it. Your setup of subtasks is perfect and easy to follow.

**Review by laurensruiz — APPROVED** [review]
Thank you for organizing this! This will be a lot of help in the future of developing the site.

**Review by AnthonyLayne — APPROVED** [review]
Looks great!  It is clear, concise and easy to understand. I appreciate the clear division between tasks and how the titles of the tasks are a different color than the descriptions. Great job!

**Review by techlando — APPROVED** [review]
Thanks for tackling this. Good job, its very easy to read

**Pull request merged**
