### PR TITLE
BL-196 create-payment-flow-prototype-in-figma Co-authored-by: Michael…

### PR DESCRIPTION
**Pull request by dirkknibbe**
…-Subbarao <Subbarao.Michael@gmail.com>

## Description

Michael and I followed the desire of our design manager Swapnali to clean up and modernize the design and get rid of redundant menus, we stayed within the more cleaned-up theme that Savannah was also working on, to keep it consistent. 

#### Video Link

https://www.loom.com/share/08bc40b899334929a027d1570c30209d

#### Jira Link

https://bloomtechlabs.atlassian.net/browse/BL-196?atlOrigin=eyJpIjoiNDcwNDM0MjY2NGVlNDNjNWE3OTg1NjMyODdkNGU0ZjgiLCJwIjoiaiJ9

## Checklist:

- [x] My design/diagram follows the style guidelines of this project
- [x] My docs are organized within an appropriate folder structure in our repo
- [x] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Comment by savmaxwell93** [comment]
These look great! Good job updating them to a cleaner and more modern feel. I really like the modal idea for donations.

**Comment by wreck888** [comment]
Great job! Love the new color changes as it helps the buttons and important information become more of the main focus! Donations feature is a great addon!

**Review by spencerlonghurst — APPROVED** [review]
It looks great! I also like the color change, it goes a lot more in alignment with the rest of the page. The payment page looks clean and trustworthy and doesn't look like some scammy/sketchy website trying to steal your money. Great job guys!

**Review by leewp8 — APPROVED** [review]
The changes you two are made are a definite improvement. It flows well and doesn't look as childish as before. The kids aren't paying!

**Review by Ogden-R — APPROVED** [review]
i love how clean the new design looks, as well as the little details that you added to make this a more user friendly webpage. great job!

**Review by ShahWahidy — COMMENTED** [review]
well done guys! this design looks much easier. This flow will make it easier for users to follow the prompts easily and don't have to go through redundant steps. great initiative on adding the donation section.

**Pull request merged**
