### PR TITLE
BL-473-Design-the-Course-Registration-page-with-advanced-filtering-op…

### PR DESCRIPTION
**Pull request by AnthonyLayne**
## Description

Designed UX artifacts for a simpler course list and registration page. Also designed an advanced filter to help choose a  course when registering. During this process, there was the intention that the parent can only book for one course at a time. The courses are also listed within each program card for easy access.

#### Video Link

(https://www.loom.com/share/8ce9de44ce4445e2aec16a3a79293321)

## Checklist:

- [ X] Designed program cards that list out the available courses. 
- [ X] Designed an advanced search/filter button under the main search bar, that only appears once clicked by the user.

### CODE REVIEW

**Review by Rebecca-Stone — APPROVED** [review]
I like the drop down of options, it will be very helpful when implemented. Great job on your loom video as well!

**Review by Rlauckern — APPROVED** [review]
Awesome loom video and great design for the advanced search modal.

**Review by Irving-Delgad0 — APPROVED** [review]
Awesome design and good implementation on search and filters!

**Review by dshipuk — APPROVED** [review]
Looking great! Unique way of showing the courses but looks great!

**Pull request merged**
