### PR TITLE
BL-97 create student flow prototype in figma/ Subtasks BL-100, 101, 103, 105, 107, 109

### PR DESCRIPTION
**Pull request by savmaxwell93**
## Description

Created the Student Flow prototype in Figma following Swapnali's advice to make it cleaner and more modern.

#### Video Link

https://www.loom.com/share/9584e8afa1c2404e9d7fe0ae4b94e3fb

#### Jira Link

https://bloomtechlabs.atlassian.net/browse/BL-97

## Checklist:

- [x] My design/diagram follows the style guidelines of this project
- [x] My docs are organized within an appropriate folder structure in our repo
- [x] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by wreck888 — COMMENTED** [review]
Looks great! I like how you cleaned up the side bar and took the student name nav bar out and moved it to the header. Good idea keeping it cleaner and making the cards bigger so it'll be more of the focal point for the children.

**Review by ShahWahidy — APPROVED** [review]
Great work Savannah. It was such a great experience collaborating with you in designing and coding these designs into components. You have done a great job of restructuring and making everything so visible. I like how you design the cards to flip on click and give more information about a particular achievement or goal! Looking forward to work with you on future issues/tickets.

**Review by wreck888 — APPROVED** [review]

**Review by spencerlonghurst — APPROVED** [review]
Great job overall! These were super helpful as we were working on building out the components. You put a ton of time into these and it really paid off and looks awesome!

**Review by leewp8 — APPROVED** [review]
This is AMAZING work. I've talked to Savannah personally about how much time and effort she put into this redesign and it was definitely all very worth it. Such a great job. And our Figma is so much easier to use now!

**Review by Ogden-R — APPROVED** [review]
Very nice. i love how you cleaned up the flow and the pages with the students in mind. it can be very overwhelming to log in to something and have no idea where to go and what to do, so its is fantastic that you were able to not only make it more functional, but also more fun for the students to explore!

**Review by dirkknibbe — APPROVED** [review]
Awesome work Savannah! Very thorough and complete, good job consulting with Swapnali on the design, and I'm sure the team was super happy to have those wireframes to help with their design 👍

**Pull request merged**
