### PR TITLE
added images and .md file

### PR DESCRIPTION
**Pull request by Ogden-R**
## Description

We created a new set of site fonts to be used on the app and applied it in figma to show what it looks like. Everything looks uniform now.

#### Team Members
Rebecca Ogden
Savannah Maxwell
Conrad Klek

#### Video Link

](https://www.loom.com/share/a913c0fb39354eb9ade49f167e16f427)

#### Trello Link

(https://bloomtechlabs.atlassian.net/browse/BL-502?atlOrigin=eyJpIjoiYmUxNzAyYjViYTVkNDNiOGI5Zjc1YTVkOTVlYzJiYTEiLCJwIjoiaiJ9)

(Example below):

<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JfipwNkb&#x2F;265-fix-refactor-sidebar-to-have-icons-representing-each-element-in-the-sidebar">Fix: Refactor sidebar to have icons representing each element in the sidebar</a></blockquote>

## Checklist:

- [x] My design/diagram follows the style guidelines of this project
- [x] My docs are organized within an appropriate folder structure in our repo
- [x] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by XavierTwitty — APPROVED** [review]
Looks good , I like the choice of font styling

**Review by theecolya — APPROVED** [review]
Looks nice and clean!

**Review by Epeng1994 — APPROVED** [review]
Looks very stylish!

**Review by lailaarkadan — APPROVED** [review]
Good job on the font style, everything looks nice and uniform.

**Review by jzkime — APPROVED** [review]
Good choice of fonts and readability for future reference!

**Comment by CameronRuch** [comment]
I like how yall put the before and after for comparison, and Roboto Mono seems to flow really nice with the website!

**Pull request merged**
