### PR TITLE
Bl 516 update product doc repository

### PR DESCRIPTION
**Pull request by ColtenEmpey**
## Description

For this ticket I used Markdown to create an Md file that describes the tasks we needed to complete and lists who completed them. 

#### Video Link

[Loom Video](https://www.loom.com/share/fd286981f33940fcb859bc4d8da4ab55)

#### Jira Link

[Update product doc repository to include updated participation details](https://bloomtechlabs.atlassian.net/browse/BL-516)

## Checklist:

- [x] My design/diagram follows the style guidelines of this project
- [x] My docs are organized within an appropriate folder structure in our repo
- [x] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by techlando — APPROVED** [review]
Great organization. I like the fact it shows who completed the task!

**Review by dirkknibbe — APPROVED** [review]
Nice job! super clean and well organized, great that the documentation can include those who have contributed

**Review by laurensruiz — APPROVED** [review]
This is great and really like how you can add who did which task.

**Review by AnthonyLayne — APPROVED** [review]
This is great, it isn't overly complicated and is well organized. It's just a suggestion, but perhaps putting a line of space between each task might help with readability.

**Review by Rlauckern — APPROVED** [review]
Nice, simple, clean, and shows who contributed what.

**Review by Rebecca-Stone — APPROVED** [review]
Looks great! I really like the table you put in, makes it a lot easier to follow along. I also really like how you linked the peoples github.

**Pull request merged**
